# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scenario.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'scenario.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import position_pb2 as position__pb2
from . import path_pb2 as path__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0escenario.proto\x12\x08pisa_api\x1a\x0eposition.proto\x1a\npath.proto\"\xa4\x02\n\x0cScenarioPack\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08map_name\x18\x02 \x01(\t\x12\x38\n\tscenarios\x18\x03 \x03(\x0b\x32%.pisa_api.ScenarioPack.ScenariosEntry\x12-\n\x10param_range_file\x18\x04 \x01(\x0b\x32\x0e.pisa_api.PathH\x00\x88\x01\x01\x12 \n\x03\x65go\x18\x05 \x01(\x0b\x32\x13.pisa_api.EgoConfig\x12\x12\n\ntimeout_ns\x18\x06 \x01(\x03\x1a@\n\x0eScenariosEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1d\n\x05value\x18\x02 \x01(\x0b\x32\x0e.pisa_api.Path:\x02\x38\x01\x42\x13\n\x11_param_range_file\"y\n\tEgoConfig\x12\x14\n\x0ctarget_speed\x18\x01 \x01(\x01\x12+\n\x0cspawn_config\x18\x02 \x01(\x0b\x32\x15.pisa_api.SpawnConfig\x12)\n\x0bgoal_config\x18\x03 \x01(\x0b\x32\x14.pisa_api.GoalConfig\"B\n\x0bSpawnConfig\x12$\n\x08position\x18\x01 \x01(\x0b\x32\x12.pisa_api.Position\x12\r\n\x05speed\x18\x02 \x01(\x01\"2\n\nGoalConfig\x12$\n\x08position\x18\x01 \x01(\x0b\x32\x12.pisa_api.Positionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scenario_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCENARIOPACK_SCENARIOSENTRY']._loaded_options = None
  _globals['_SCENARIOPACK_SCENARIOSENTRY']._serialized_options = b'8\001'
  _globals['_SCENARIOPACK']._serialized_start=57
  _globals['_SCENARIOPACK']._serialized_end=349
  _globals['_SCENARIOPACK_SCENARIOSENTRY']._serialized_start=264
  _globals['_SCENARIOPACK_SCENARIOSENTRY']._serialized_end=328
  _globals['_EGOCONFIG']._serialized_start=351
  _globals['_EGOCONFIG']._serialized_end=472
  _globals['_SPAWNCONFIG']._serialized_start=474
  _globals['_SPAWNCONFIG']._serialized_end=540
  _globals['_GOALCONFIG']._serialized_start=542
  _globals['_GOALCONFIG']._serialized_end=592
# @@protoc_insertion_point(module_scope)
