# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import av_server_pb2 as av__server__pb2
from . import empty_pb2 as empty__pb2
from . import pong_pb2 as pong__pb2


class AvServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/sbsvf_api.AvServer/Ping',
                request_serializer=empty__pb2.Empty.SerializeToString,
                response_deserializer=pong__pb2.Pong.FromString,
                )
        self.Init = channel.unary_unary(
                '/sbsvf_api.AvServer/Init',
                request_serializer=av__server__pb2.AvServerMessages.InitRequest.SerializeToString,
                response_deserializer=av__server__pb2.AvServerMessages.InitResponse.FromString,
                )
        self.Reset = channel.unary_unary(
                '/sbsvf_api.AvServer/Reset',
                request_serializer=av__server__pb2.AvServerMessages.ResetRequest.SerializeToString,
                response_deserializer=av__server__pb2.AvServerMessages.ResetResponse.FromString,
                )
        self.Step = channel.unary_unary(
                '/sbsvf_api.AvServer/Step',
                request_serializer=av__server__pb2.AvServerMessages.StepRequest.SerializeToString,
                response_deserializer=av__server__pb2.AvServerMessages.StepResponse.FromString,
                )
        self.Stop = channel.unary_unary(
                '/sbsvf_api.AvServer/Stop',
                request_serializer=empty__pb2.Empty.SerializeToString,
                response_deserializer=empty__pb2.Empty.FromString,
                )
        self.ShouldQuit = channel.unary_unary(
                '/sbsvf_api.AvServer/ShouldQuit',
                request_serializer=empty__pb2.Empty.SerializeToString,
                response_deserializer=av__server__pb2.AvServerMessages.ShouldQuitResponse.FromString,
                )


class AvServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Check if the server is alive
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Init(self, request, context):
        """Initialize the AV system with configuration parameters
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Reset the AV system with a new scenario and initial observation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Step(self, request, context):
        """Advance the AV system by one step with the provided observation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Stop the AV system
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShouldQuit(self, request, context):
        """Check if the AV system should quit
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AvServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=empty__pb2.Empty.FromString,
                    response_serializer=pong__pb2.Pong.SerializeToString,
            ),
            'Init': grpc.unary_unary_rpc_method_handler(
                    servicer.Init,
                    request_deserializer=av__server__pb2.AvServerMessages.InitRequest.FromString,
                    response_serializer=av__server__pb2.AvServerMessages.InitResponse.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=av__server__pb2.AvServerMessages.ResetRequest.FromString,
                    response_serializer=av__server__pb2.AvServerMessages.ResetResponse.SerializeToString,
            ),
            'Step': grpc.unary_unary_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=av__server__pb2.AvServerMessages.StepRequest.FromString,
                    response_serializer=av__server__pb2.AvServerMessages.StepResponse.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=empty__pb2.Empty.FromString,
                    response_serializer=empty__pb2.Empty.SerializeToString,
            ),
            'ShouldQuit': grpc.unary_unary_rpc_method_handler(
                    servicer.ShouldQuit,
                    request_deserializer=empty__pb2.Empty.FromString,
                    response_serializer=av__server__pb2.AvServerMessages.ShouldQuitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sbsvf_api.AvServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AvServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sbsvf_api.AvServer/Ping',
            empty__pb2.Empty.SerializeToString,
            pong__pb2.Pong.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sbsvf_api.AvServer/Init',
            av__server__pb2.AvServerMessages.InitRequest.SerializeToString,
            av__server__pb2.AvServerMessages.InitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sbsvf_api.AvServer/Reset',
            av__server__pb2.AvServerMessages.ResetRequest.SerializeToString,
            av__server__pb2.AvServerMessages.ResetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sbsvf_api.AvServer/Step',
            av__server__pb2.AvServerMessages.StepRequest.SerializeToString,
            av__server__pb2.AvServerMessages.StepResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sbsvf_api.AvServer/Stop',
            empty__pb2.Empty.SerializeToString,
            empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ShouldQuit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sbsvf_api.AvServer/ShouldQuit',
            empty__pb2.Empty.SerializeToString,
            av__server__pb2.AvServerMessages.ShouldQuitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
