# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import empty_pb2 as empty__pb2
from . import pong_pb2 as pong__pb2
from . import sim_server_pb2 as sim__server__pb2


class SimServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/sbsvf_api.SimServer/Ping',
                request_serializer=empty__pb2.Empty.SerializeToString,
                response_deserializer=pong__pb2.Pong.FromString,
                )
        self.Init = channel.unary_unary(
                '/sbsvf_api.SimServer/Init',
                request_serializer=sim__server__pb2.SimServerMessages.InitRequest.SerializeToString,
                response_deserializer=sim__server__pb2.SimServerMessages.InitResponse.FromString,
                )
        self.Reset = channel.unary_unary(
                '/sbsvf_api.SimServer/Reset',
                request_serializer=sim__server__pb2.SimServerMessages.ResetRequest.SerializeToString,
                response_deserializer=sim__server__pb2.SimServerMessages.ResetResponse.FromString,
                )
        self.Step = channel.unary_unary(
                '/sbsvf_api.SimServer/Step',
                request_serializer=sim__server__pb2.SimServerMessages.StepRequest.SerializeToString,
                response_deserializer=sim__server__pb2.SimServerMessages.StepResponse.FromString,
                )
        self.Stop = channel.unary_unary(
                '/sbsvf_api.SimServer/Stop',
                request_serializer=empty__pb2.Empty.SerializeToString,
                response_deserializer=empty__pb2.Empty.FromString,
                )
        self.ShouldQuit = channel.unary_unary(
                '/sbsvf_api.SimServer/ShouldQuit',
                request_serializer=empty__pb2.Empty.SerializeToString,
                response_deserializer=sim__server__pb2.SimServerMessages.ShouldQuitResponse.FromString,
                )


class SimServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Check if the server is alive
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Init(self, request, context):
        """Initialize the simulation (e.g., load maps, set weather)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Reset the simulation with a new scenario
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Step(self, request, context):
        """Advance the simulation by one step with the provided control command
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Stop the simulation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShouldQuit(self, request, context):
        """Check if the simulation should quit
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=empty__pb2.Empty.FromString,
                    response_serializer=pong__pb2.Pong.SerializeToString,
            ),
            'Init': grpc.unary_unary_rpc_method_handler(
                    servicer.Init,
                    request_deserializer=sim__server__pb2.SimServerMessages.InitRequest.FromString,
                    response_serializer=sim__server__pb2.SimServerMessages.InitResponse.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=sim__server__pb2.SimServerMessages.ResetRequest.FromString,
                    response_serializer=sim__server__pb2.SimServerMessages.ResetResponse.SerializeToString,
            ),
            'Step': grpc.unary_unary_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=sim__server__pb2.SimServerMessages.StepRequest.FromString,
                    response_serializer=sim__server__pb2.SimServerMessages.StepResponse.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=empty__pb2.Empty.FromString,
                    response_serializer=empty__pb2.Empty.SerializeToString,
            ),
            'ShouldQuit': grpc.unary_unary_rpc_method_handler(
                    servicer.ShouldQuit,
                    request_deserializer=empty__pb2.Empty.FromString,
                    response_serializer=sim__server__pb2.SimServerMessages.ShouldQuitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sbsvf_api.SimServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SimServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sbsvf_api.SimServer/Ping',
            empty__pb2.Empty.SerializeToString,
            pong__pb2.Pong.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sbsvf_api.SimServer/Init',
            sim__server__pb2.SimServerMessages.InitRequest.SerializeToString,
            sim__server__pb2.SimServerMessages.InitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sbsvf_api.SimServer/Reset',
            sim__server__pb2.SimServerMessages.ResetRequest.SerializeToString,
            sim__server__pb2.SimServerMessages.ResetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sbsvf_api.SimServer/Step',
            sim__server__pb2.SimServerMessages.StepRequest.SerializeToString,
            sim__server__pb2.SimServerMessages.StepResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sbsvf_api.SimServer/Stop',
            empty__pb2.Empty.SerializeToString,
            empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ShouldQuit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sbsvf_api.SimServer/ShouldQuit',
            empty__pb2.Empty.SerializeToString,
            sim__server__pb2.SimServerMessages.ShouldQuitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
